/**
 * This file is autogenerated by `deploy` script.
 * You should not edit it manually or your changes might be overwritten.
 */

export type ContractName = "Wallet";

export type ChainId = 11155111 | 17000 | 31337;

export default {
  "17000": {
    "Wallet": {
      "address": "0xc76D8178D3cA360B3A8D0bb643a963f4e5df2340",
      "abi": [
        {
          "inputs": [],
          "stateMutability": "nonpayable",
          "type": "constructor"
        },
        {
          "inputs": [],
          "name": "Wallet__AmountCannotBeZero",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumCannotMoreThanOwners",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__NotEnoughBalance",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyOwnner",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanCancel",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanSend",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OwnersIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__RequestorCannotConfirm",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadyConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadySent",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionIsCanceled",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotExists",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionSendFailed",
          "type": "error"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "DepositAmount",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionCanceled",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum Wallet.ConfirmStatus",
              "name": "status",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionConfirmed",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionRequested",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionSend",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum UserWalletStorage.WalletType",
              "name": "walletType",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address[]",
              "name": "owners",
              "type": "address[]"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "WalletCreated",
          "type": "event"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "cancelTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            },
            {
              "internalType": "bool",
              "name": "_confirm",
              "type": "bool"
            }
          ],
          "name": "confirmTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address[]",
              "name": "_owners",
              "type": "address[]"
            },
            {
              "internalType": "string",
              "name": "_name",
              "type": "string"
            },
            {
              "internalType": "uint256",
              "name": "_needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "createWallet",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "deposit",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "getUserWallets",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "string",
                  "name": "name",
                  "type": "string"
                },
                {
                  "internalType": "enum UserWalletStorage.WalletType",
                  "name": "walletType",
                  "type": "uint8"
                },
                {
                  "internalType": "address[]",
                  "name": "owners",
                  "type": "address[]"
                },
                {
                  "internalType": "uint256",
                  "name": "balance",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "needComfirmCount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct UserWalletStorage.UserWallet[]",
              "name": "",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletDeposits",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "owner",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct Wallet.Deposit[]",
              "name": "deposits",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletTransactions",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "from",
                  "type": "address"
                },
                {
                  "internalType": "address",
                  "name": "to",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                },
                {
                  "internalType": "enum WalletTransactionStorage.TransactionStatus",
                  "name": "status",
                  "type": "uint8"
                },
                {
                  "internalType": "string",
                  "name": "description",
                  "type": "string"
                },
                {
                  "internalType": "uint256",
                  "name": "confirmedCount",
                  "type": "uint256"
                }
              ],
              "internalType": "struct WalletTransactionStorage.Transaction[]",
              "name": "",
              "type": "tuple[]"
            },
            {
              "internalType": "enum Wallet.ConfirmStatus[]",
              "name": "",
              "type": "uint8[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "_to",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "_amount",
              "type": "uint256"
            },
            {
              "internalType": "string",
              "name": "_description",
              "type": "string"
            }
          ],
          "name": "requestTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "sendTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        }
      ],
      "inheritedFunctions": {}
    }
  },
  "31337": {
    "Wallet": {
      "address": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      "abi": [
        {
          "inputs": [],
          "name": "Wallet__AmountCannotBeZero",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumCannotMoreThanOwners",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__NotEnoughBalance",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyOwnner",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanCancel",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanSend",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OwnersIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__RequestorCannotConfirm",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadyConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadySent",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionIsCanceled",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotExists",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionSendFailed",
          "type": "error"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "DepositAmount",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionCanceled",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum Wallet.ConfirmStatus",
              "name": "status",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionConfirmed",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionRequested",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionSend",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum UserWalletStorage.WalletType",
              "name": "walletType",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address[]",
              "name": "owners",
              "type": "address[]"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "WalletCreated",
          "type": "event"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "cancelTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            },
            {
              "internalType": "bool",
              "name": "_confirm",
              "type": "bool"
            }
          ],
          "name": "confirmTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address[]",
              "name": "_owners",
              "type": "address[]"
            },
            {
              "internalType": "string",
              "name": "_name",
              "type": "string"
            },
            {
              "internalType": "uint256",
              "name": "_needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "createWallet",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "deposit",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "getUserWallets",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "string",
                  "name": "name",
                  "type": "string"
                },
                {
                  "internalType": "enum UserWalletStorage.WalletType",
                  "name": "walletType",
                  "type": "uint8"
                },
                {
                  "internalType": "address[]",
                  "name": "owners",
                  "type": "address[]"
                },
                {
                  "internalType": "uint256",
                  "name": "balance",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "needComfirmCount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct UserWalletStorage.UserWallet[]",
              "name": "",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletDeposits",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "owner",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct Wallet.Deposit[]",
              "name": "deposits",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletTransactions",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "from",
                  "type": "address"
                },
                {
                  "internalType": "address",
                  "name": "to",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                },
                {
                  "internalType": "enum WalletTransactionStorage.TransactionStatus",
                  "name": "status",
                  "type": "uint8"
                },
                {
                  "internalType": "string",
                  "name": "description",
                  "type": "string"
                },
                {
                  "internalType": "uint256",
                  "name": "confirmedCount",
                  "type": "uint256"
                }
              ],
              "internalType": "struct WalletTransactionStorage.Transaction[]",
              "name": "",
              "type": "tuple[]"
            },
            {
              "internalType": "enum Wallet.ConfirmStatus[]",
              "name": "",
              "type": "uint8[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "_to",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "_amount",
              "type": "uint256"
            },
            {
              "internalType": "string",
              "name": "_description",
              "type": "string"
            }
          ],
          "name": "requestTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint256",
              "name": "_tokenId",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "_salePrice",
              "type": "uint256"
            }
          ],
          "name": "royaltyInfo",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "sendTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes4",
              "name": "interfaceId",
              "type": "bytes4"
            }
          ],
          "name": "supportsInterface",
          "outputs": [
            {
              "internalType": "bool",
              "name": "",
              "type": "bool"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        }
      ],
      "inheritedFunctions": {
        "royaltyInfo": "@openzeppelin/contracts/token/common/ERC2981.sol",
        "supportsInterface": "@openzeppelin/contracts/token/common/ERC2981.sol"
      }
    }
  },
  "11155111": {
    "Wallet": {
      "address": "0x76E07996D32683F54A319Cf7B0C937Bc5362529a",
      "abi": [
        {
          "inputs": [],
          "stateMutability": "nonpayable",
          "type": "constructor"
        },
        {
          "inputs": [],
          "name": "Wallet__AmountCannotBeZero",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumCannotMoreThanOwners",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__ConfirmNumIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__NotEnoughBalance",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyOwnner",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanCancel",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OnlyRequestorCanSend",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__OwnersIsRequired",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__RequestorCannotConfirm",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadyConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionAlreadySent",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionIsCanceled",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotConfirmed",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionNotExists",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "Wallet__TransactionSendFailed",
          "type": "error"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "DepositAmount",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionCanceled",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum Wallet.ConfirmStatus",
              "name": "status",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "userAddress",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionConfirmed",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionRequested",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "from",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "bytes32",
              "name": "transactionId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "to",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "timestamp",
              "type": "uint256"
            }
          ],
          "name": "TransactionSend",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "walletId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum UserWalletStorage.WalletType",
              "name": "walletType",
              "type": "uint8"
            },
            {
              "indexed": true,
              "internalType": "address[]",
              "name": "owners",
              "type": "address[]"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "WalletCreated",
          "type": "event"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "cancelTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            },
            {
              "internalType": "bool",
              "name": "_confirm",
              "type": "bool"
            }
          ],
          "name": "confirmTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address[]",
              "name": "_owners",
              "type": "address[]"
            },
            {
              "internalType": "string",
              "name": "_name",
              "type": "string"
            },
            {
              "internalType": "uint256",
              "name": "_needComfirmCount",
              "type": "uint256"
            }
          ],
          "name": "createWallet",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "deposit",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "getUserWallets",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "string",
                  "name": "name",
                  "type": "string"
                },
                {
                  "internalType": "enum UserWalletStorage.WalletType",
                  "name": "walletType",
                  "type": "uint8"
                },
                {
                  "internalType": "address[]",
                  "name": "owners",
                  "type": "address[]"
                },
                {
                  "internalType": "uint256",
                  "name": "balance",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "needComfirmCount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct UserWalletStorage.UserWallet[]",
              "name": "",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletDeposits",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "owner",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                }
              ],
              "internalType": "struct Wallet.Deposit[]",
              "name": "deposits",
              "type": "tuple[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            }
          ],
          "name": "getWalletTransactions",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "id",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "from",
                  "type": "address"
                },
                {
                  "internalType": "address",
                  "name": "to",
                  "type": "address"
                },
                {
                  "internalType": "uint256",
                  "name": "amount",
                  "type": "uint256"
                },
                {
                  "internalType": "uint256",
                  "name": "timestamp",
                  "type": "uint256"
                },
                {
                  "internalType": "enum WalletTransactionStorage.TransactionStatus",
                  "name": "status",
                  "type": "uint8"
                },
                {
                  "internalType": "string",
                  "name": "description",
                  "type": "string"
                },
                {
                  "internalType": "uint256",
                  "name": "confirmedCount",
                  "type": "uint256"
                }
              ],
              "internalType": "struct WalletTransactionStorage.Transaction[]",
              "name": "",
              "type": "tuple[]"
            },
            {
              "internalType": "enum Wallet.ConfirmStatus[]",
              "name": "",
              "type": "uint8[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "_to",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "_amount",
              "type": "uint256"
            },
            {
              "internalType": "string",
              "name": "_description",
              "type": "string"
            }
          ],
          "name": "requestTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "_walletId",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "_transactionId",
              "type": "bytes32"
            }
          ],
          "name": "sendTransaction",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        }
      ],
      "inheritedFunctions": {}
    }
  }
} as const;
